spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: delivery-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topic:
      payment-completed: payment-completed-topic

logging:
  level:
    root: INFO

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health,info
